wandb_version: 1

data_path:
  desc: null
  value: data/TT_100K_det.yaml
conf_file:
  desc: null
  value: configs/yolov6m6_finetune.py
img_size:
  desc: null
  value: 640
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 500
workers:
  desc: null
  value: 4
device:
  desc: null
  value: 2,3
eval_interval:
  desc: null
  value: 20
eval_final_only:
  desc: null
  value: true
heavy_eval_range:
  desc: null
  value: 50
check_images:
  desc: null
  value: false
check_labels:
  desc: null
  value: false
output_dir:
  desc: null
  value: ./runs/train
name:
  desc: null
  value: exp
dist_url:
  desc: null
  value: env://
gpu_count:
  desc: null
  value: 0
segonly:
  desc: null
  value: 'False'
detonly:
  desc: null
  value: 'True'
clsonly:
  desc: null
  value: 'False'
local_rank:
  desc: null
  value: 1
resume:
  desc: null
  value: false
skip:
  desc: null
  value: 'False'
write_trainbatch_tb:
  desc: null
  value: false
stop_aug_last_n_epoch:
  desc: null
  value: 15
save_ckpt_on_last_n_epoch:
  desc: null
  value: -1
distill:
  desc: null
  value: false
distill_feat:
  desc: null
  value: false
quant:
  desc: null
  value: false
calib:
  desc: null
  value: false
teacher_model_path:
  desc: null
  value: null
temperature:
  desc: null
  value: 20
fuse_ab:
  desc: null
  value: false
bs_per_gpu:
  desc: null
  value: 16
freeze_backbone:
  desc: null
  value: 0
rank:
  desc: null
  value: 1
world_size:
  desc: null
  value: 2
save_dir:
  desc: null
  value: runs/train/exp48
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703586774.569748
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
